/**
 * Parent-Version Migration Fixture Test (issue #220)
 *
 * Usage: node tests/run-electron-node-test.cjs tests/migration-v56-to-v57.test.ts
 *
 * tests/upgrade-path.test.ts only ever exercises one fixture: a v1.5.0-era
 * database run through the *entire* migration chain. That catches bugs a
 * fresh install can't see, but it can't catch a migration that only
 * conflicts with the specific schema shape immediately before it — the
 * kind of bug that surfaces when two branches each add a migration off the
 * same parent version and one of them assumed a shape the other changed.
 *
 * This test freezes a fixture at schema v56 (tests/fixtures/upgrade-
 * snapshots/schema-v56-pre-tax-registration-rename.db, generated by
 * scripts/generate-upgrade-fixture.ts — see that file's own header) — the
 * exact parent version migration v57 (rename_gstin_to_generic_tax_
 * registration_number, main/db.ts) was written against — seeds it with the
 * pre-rename settings keys a real v56 install would have, and asserts v57
 * carries them forward correctly on top of that real, non-synthetic shape.
 *
 * One wrinkle the fixture generator can't avoid: it runs migration v1
 * (createSchema()) with *today's* source, which already seeds the renamed
 * 'tax_registration_number' key — a real install that reached v56 before
 * this rename shipped never had that row, only 'gstin'. This test deletes
 * the generator's retroactively-seeded row before reseeding 'gstin', so the
 * fixture matches what a real pre-rename install's settings table actually
 * looks like; otherwise v57's `INSERT OR IGNORE` silently no-ops against
 * the already-present empty row and the real gstin value is lost.
 */
import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

const Module = require('module');
const originalLoad = Module._load;
const testDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flo-migration-v56-v57-'));

const FIXTURE = path.join(__dirname, 'fixtures/upgrade-snapshots/schema-v56-pre-tax-registration-rename.db');
const dbPath = path.join(testDir, 'flo.db');
fs.copyFileSync(FIXTURE, dbPath);

const FixtureDatabase = require('better-sqlite3');
const fixtureDb = new FixtureDatabase(dbPath);
assert.equal(fixtureDb.pragma('user_version', { simple: true }), 56, 'fixture is frozen at schema v56');
fixtureDb.prepare(`DELETE FROM settings WHERE key IN ('tax_registration_number', 'bill_show_tax_id')`).run();
fixtureDb.prepare(`
  INSERT OR REPLACE INTO settings (key, value, updated_at) VALUES
    ('gstin', '29ABCDE1234F1Z5', CURRENT_TIMESTAMP),
    ('bill_show_gstn', '1', CURRENT_TIMESTAMP)
`).run();
fixtureDb.close();

const mockApp = {
  isPackaged: true,
  getPath: (_name: string) => testDir,
  getVersion: () => 'test',
};
Module._load = function (request: string, parent: unknown, isMain: boolean) {
  if (request === 'electron') return { app: mockApp };
  return originalLoad.apply(this, arguments as any);
};

function isNativeAbiMismatch(error: any): boolean {
  return error?.code === 'ERR_DLOPEN_FAILED'
    && String(error?.message || '').includes('NODE_MODULE_VERSION');
}

function main() {
  console.log('🧪 Migration v56 → v57 Parent-Version Fixture Test');
  console.log('='.repeat(60));

  const { initDatabase, getDatabase, closeDatabase, getCurrentSchemaVersion, buildIdealSchemaDb } = require('../main/db');

  try {
    initDatabase();
  } catch (error: any) {
    if (isNativeAbiMismatch(error)) {
      console.log('   ⚠ Skipping: better-sqlite3 is not built for this shell Node ABI.');
      process.exit(77);
    }
    throw new Error(`migrating a real v56 install crashed: ${error.message}`);
  }

  const db = getDatabase();
  const ideal = buildIdealSchemaDb();
  const latestSchemaVersion = ideal.pragma('user_version', { simple: true }) as number;
  ideal.close();
  assert.equal(getCurrentSchemaVersion(), latestSchemaVersion,
    'a real v56 install reaches the same schema version as a fresh install');
  console.log(`   ✓ v56 fixture migrates cleanly to v${latestSchemaVersion}`);

  const registrationNumber = db.prepare(
    `SELECT value FROM settings WHERE key = 'tax_registration_number'`
  ).get() as { value: string } | undefined;
  assert.equal(registrationNumber?.value, '29ABCDE1234F1Z5',
    'v57 copies a real v56 install\'s gstin value forward to tax_registration_number');

  const showTaxId = db.prepare(
    `SELECT value FROM settings WHERE key = 'bill_show_tax_id'`
  ).get() as { value: string } | undefined;
  assert.equal(showTaxId?.value, '1',
    'v57 copies a real v56 install\'s bill_show_gstn value forward to bill_show_tax_id');

  const oldGstin = db.prepare(`SELECT value FROM settings WHERE key = 'gstin'`).get() as { value: string } | undefined;
  assert.equal(oldGstin?.value, '29ABCDE1234F1Z5', 'the old gstin row is left in place, not deleted');

  console.log('   ✓ v57 preserves and forwards the old gstin/bill_show_gstn keys on a real pre-rename install');

  closeDatabase();
  console.log('='.repeat(60));
  console.log('✅ Migration v56 → v57 fixture test passed');
}

main();
